#!/usr/bin/env bash
# Configure my domain zone

dis () {
  ip=$(dig "$2.$1" | grep -A1 ';; ANSWER SECTION:' | sed '1d' | awk '{print $5}')
  rec=$(dig "$2.$1" | grep -A1 ';; ANSWER SECTION:' | sed '1d' | awk '{print $4}')
  echo "The subdomain $2 is a $rec record and points to $ip"
}

if [ "$#" -lt 2 ]; then

  dis "$1" www
  dis "$1" lb-01
  dis "$1" web-01
  dis "$1" web-02 

else

  dis "$1" "$2"

fi
