#!/usr/bin/env bash
# print 10 times Best School whith if

i=0
while [ $i -le 10 ]
do
    i=$((i + 1))
    if [ $i -eq 4 ]
    then
        echo bad luck
    elif [ $i -eq 8 ]
    then
        echo good luck
    else
        echo Best School
    fi
done