#!/usr/bin/env bash
# print 10 times Best School whith if

i=1
while [ $i -le 12 ]
do
    j=1
    while [ $j -le 59 ]
    do
        echo $j
        j=$((j + 1))
    done
    echo Hour: $i
    i=$((i + 1))
done