#!/usr/bin/env bash
#install the ufw firewall and setup a few rules on

sudo apt update
sudo apt install ufw

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw default deny incoming
sudo ufw enable
